# Generated by Django 2.1 on 2018-09-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='allow_token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
