# Generated by Django 2.1.1 on 2018-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorization_app', '0002_products_allow_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='allow_token',
            field=models.CharField(default='', max_length=10),
        ),
    ]
